services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: <senin-bot-tokenin>
      - key: WEBHOOK_URL
        value: https://telegram-bot-3rda.onrender.com
